[package]
name = "positive_mahjong"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "pmj_client"
path = "src/client/client.rs"

[[bin]]
name = "pmj_server"
path = "src/server/server.rs"

[dependencies]
local-ip-address = "0.6.10"
reqwest = { version = "0.13.2", features = ["json"] }
serde = { version = "1.0.228", features = ["serde_derive"] }
serde_json = "1.0.149"
tiny_http = "0.12.0"
tokio = { version = "1.49.0", features = ["full"] }
